using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

const int EntryIndexBitCount = 9;
const uint EntryIndexMask = (1u << EntryIndexBitCount) - 1;

string repositoryRoot = FindRepositoryRoot(Directory.GetCurrentDirectory());
string dataPath = Path.Combine(repositoryRoot, "src", "BlueBird.Pinyins", "PinyinData.cs");
string indexPath = Path.Combine(repositoryRoot, "src", "BlueBird.Pinyins", "PinyinIndex.cs");

string dataSource = File.ReadAllText(dataPath, Encoding.UTF8);
MatchCollection matches = Regex.Matches(
    dataSource,
    """new \("(?<pinyin>[^"]+)", "(?<characters>[^"]*)"\)""",
    RegexOptions.CultureInvariant);

if (matches.Count == 0)
    throw new InvalidOperationException($"No pinyin entries were found in '{dataPath}'.");

Dictionary<int, int> characterMappings = new();
string? previousPinyin = null;

for (int entryIndex = 0; entryIndex < matches.Count; entryIndex++)
{
    if ((uint)entryIndex > EntryIndexMask)
    {
        throw new InvalidOperationException(
            $"Pinyin entry index {entryIndex} exceeds the {EntryIndexBitCount}-bit limit.");
    }

    Match match = matches[entryIndex];
    string pinyin = match.Groups["pinyin"].Value;
    string characters = match.Groups["characters"].Value;

    if (previousPinyin is not null && string.CompareOrdinal(previousPinyin, pinyin) >= 0)
    {
        throw new InvalidOperationException(
            $"Pinyin entries must be unique and ordinally sorted: '{previousPinyin}', '{pinyin}'.");
    }

    previousPinyin = pinyin;

    foreach (Rune character in characters.EnumerateRunes())
    {
        if (!characterMappings.TryAdd(character.Value, entryIndex))
        {
            int existingIndex = characterMappings[character.Value];
            throw new InvalidOperationException(
                $"Character '{character}' (U+{character.Value:X}) occurs in entries " +
                $"{existingIndex} and {entryIndex}.");
        }
    }
}

uint[] mappings = characterMappings
    .OrderBy(static pair => pair.Key)
    .Select(static pair => ((uint)pair.Key << EntryIndexBitCount) | (uint)pair.Value)
    .ToArray();

if (mappings.Length == 0)
    throw new InvalidOperationException("No character mappings were generated.");

string generatedSource = GenerateSource(mappings);
File.WriteAllText(indexPath, generatedSource, Encoding.UTF8);
Console.WriteLine($"Generated {mappings.Length} character mappings from {matches.Count} pinyin entries.");
return 0;

static string FindRepositoryRoot(string startDirectory)
{
    DirectoryInfo? directory = new(startDirectory);

    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "BlueBird.slnx")))
            return directory.FullName;

        directory = directory.Parent;
    }

    throw new InvalidOperationException($"Could not find the repository root from '{startDirectory}'.");
}

static string GenerateSource(IReadOnlyList<uint> mappings)
{
    StringBuilder builder = new();

    builder.AppendLine(
        """
        // <auto-generated />
        // Generated by BlueBird.Pinyins.IndexGenerator. Do not edit manually.

        using System.Text;

        namespace BlueBird.Pinyins
        {
            internal static class PinyinIndex
            {
                private const int EntryIndexBitCount = 9;
                private const uint EntryIndexMask = (1u << EntryIndexBitCount) - 1;

                internal static bool TryGetEntryIndex(Rune character, out ushort entryIndex)
                {
                    uint codePoint = (uint)character.Value;
                    uint minCodePoint = CharacterMappings[0] >> EntryIndexBitCount;
                    uint maxCodePoint = CharacterMappings[^1] >> EntryIndexBitCount;

                    if (codePoint < minCodePoint || codePoint > maxCodePoint)
                    {
                        entryIndex = default;
                        return false;
                    }

                    uint searchKey = codePoint << EntryIndexBitCount;
                    int start = 0;
                    int end = CharacterMappings.Length;

                    while (start < end)
                    {
                        int middle = start + ((end - start) >> 1);

                        if (CharacterMappings[middle] < searchKey)
                            start = middle + 1;
                        else
                            end = middle;
                    }

                    if ((uint)start < (uint)CharacterMappings.Length)
                    {
                        uint mapping = CharacterMappings[start];

                        if ((mapping >> EntryIndexBitCount) == codePoint)
                        {
                            entryIndex = (ushort)(mapping & EntryIndexMask);
                            return true;
                        }
                    }

                    entryIndex = default;
                    return false;
                }

                private static readonly uint[] CharacterMappings = new uint[]
                {
        """);

    const int valuesPerLine = 8;
    for (int index = 0; index < mappings.Count; index += valuesPerLine)
    {
        builder.Append("            ");
        int lineEnd = Math.Min(index + valuesPerLine, mappings.Count);

        for (int valueIndex = index; valueIndex < lineEnd; valueIndex++)
        {
            if (valueIndex > index)
                builder.Append(' ');

            builder.Append("0x");
            builder.Append(mappings[valueIndex].ToString("X8", CultureInfo.InvariantCulture));
            builder.Append("u,");
        }

        builder.AppendLine();
    }

    builder.AppendLine(
        """
                };
            }
        }
        """);

    return builder.ToString().ReplaceLineEndings("\n");
}
